CREATE SCHEMA IF NOT EXISTS client;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA client TO peak;

CREATE TABLE client.client
(
    client_id                                               SERIAL,
    individual_id                                           INTEGER  REFERENCES reference.individual (individual_id),
    platform_id                                             INTEGER NOT NULL  REFERENCES reference.platform (platform_id),
    platform_client_id                                      VARCHAR(15) NOT NULL,
    advisor_code                                            INTEGER REFERENCES advisor.advisor_code (advisor_code),
    client_status_id                                        INTEGER REFERENCES reference.status (status_id),
    document_delivery_method                                VARCHAR(20) CHECK (document_delivery_method IN ('PAPER', 'ELECTRONIC')),
    household_number										VARCHAR(255),
    household_name										    VARCHAR(255),
    household_head										    VARCHAR(255),
    other_name                                              VARCHAR(255),
    us_social_security_number                               VARCHAR(9),
    residency_for_tax_purposes                              VARCHAR(50),
    neq                                                     VARCHAR(25),
    cra_business_number                                     VARCHAR(25),
    number_of_dependant                                     SMALLINT ,
    financial_institution                                   INTEGER  REFERENCES reference.financial_institution (financial_institution_id),
    bank_transit_number                                     INTEGER ,
    bank_account_number                                     VARCHAR(30) ,
    personal_net_worth_liquid_assets                        DECIMAL(15, 2) ,
    personal_net_worth_fixed_assets                         DECIMAL(15, 2) ,
    personal_net_worth_liabilities                          DECIMAL(15, 2) ,
    personal_net_worth_total                                DECIMAL(15, 2) NOT NULL,
    estimated_annual_income                                 DECIMAL(15, 2) ,
    occupation_type                                         VARCHAR(25) CHECK (occupation_type IN ('EMPLOYED', 'SELF-EMPLOYED', 'RETIRED', 'UNEMPLOYED')),
    occupation_position                                     VARCHAR(70),
    type_of_business                                        VARCHAR(70),
    employer_name                                           VARCHAR(70),
    employer_address                                        VARCHAR(255),
    telephone_work                                          VARCHAR(20),
    number_of_years_with_current_employer                   INTEGER,
    investment_knowledge                                    VARCHAR(25)  CHECK (investment_knowledge IN ('POOR', 'FAIR', 'GOOD', 'SOPHISTICATED')),
    control_10_percent_of_a_public_company                  BOOLEAN ,
    control_10_percent_public_company_list                  TEXT,
    control_20_percent_of_a_public_company                  BOOLEAN ,
    control_20_percent_public_company_list                  TEXT,
    investment_accounts_outside_peak                        BOOLEAN ,
    investment_accounts_outside_peak_list                   TEXT,
    control_other_investment_account                        BOOLEAN,
    control_other_investment_account_qty                    INTEGER,
    foreign_pep                                             VARCHAR(50) CHECK (FOREIGN_PEP IN ('HEAD OF STATE / GOVERNMENT', 'DEPUTY MINISTER (OR EQUIVALENT)', 'MILITARY GENERAL (OR EQUIVALENT)', 'JUDGE', 'MEMBER OF THE EXECUTIVE COUNCIL OF GOVERNMENT OR MEMBER OF LEGISLATURE', 'AMBASSADOR OR AMBASSADOR''S ATTACHé OR COUNSELLOR', 'HEAD OF A GOVERNMENT AGENCY', 'LEADER OR PRESIDENT OF A POLITICAL PARTY IN A LEGISLATURE')),
    domestic_pep                                            VARCHAR(50) CHECK (DOMESTIC_PEP IN ('GOVERNOR GENERAL, LIEUTENANT GOVERNOR OR HEAD OF GOVERNMENT', 'MEMBER OF THE SENATE OR HOUSE OF COMMONS OR MEMBER OF A LEGISLATURE', 'DEPUTY MINISTER OR EQUIVALENT RANK', 'AMBASSADOR, ATTACHé OR COUNSELLOR OF AN AMBASSADOR', 'MILITARY OFFICER WITH A RANK OF GENERAL OR ABOVE', 'PRESIDENT OF A CORPORATION THAT IS WHOLLY OWNED DIRECTLY BY HER MAJESTY OF CANADA OR A PROVINCE', 'HEAD OF A GOVERNMENT AGENCY', 'JUDGE OF AN APPELLATE COURT IN A PROVINCE, THE FEDERAL COURT OF APPEAL OR THE SUPREME COURT OF CANADA', 'LEADER OR PRESIDENT OF A POLITICAL PARTY REPRESENTED IN A LEGISLATURE', 'MAYOR')),
    head_of_international_organization                      VARCHAR(50) CHECK (HEAD_OF_INTERNATIONAL_ORGANIZATION IN ('HEAD OF AN INTERNATIONAL ORGANIZATION ESTABLISHED BY THE GOVERNMENTS OF STATES', 'HEAD OF AN INSTITUTION ESTABLISHED BY AN INTERNATIONAL ORGANIZATION')),
    pep_or_hio_family_member                                BOOLEAN ,
    pep_or_hio_family_member_organization_and_position      TEXT,
    disclosure_of_beneficial_ownership_information          BOOLEAN ,
    receive_security_holder_material                        VARCHAR(50)  CHECK (receive_security_holder_material IN ('ALL', 'NONE', 'PROXY')),
    temporary_mailing_address                               INTEGER  REFERENCES reference.address (address_id),
    consolidated_objectives_and_risk                        BOOLEAN ,
    investment_objectives_income_iiroc                      INTEGER,
    investment_objectives_medium_term_growth_iiroc          INTEGER,
    investment_objectives_long_term_growth_iiroc            INTEGER,
    investment_objectives_speculation_iiroc                 INTEGER,
    investment_objectives_liquidity_mfda                    INTEGER,
    investment_objectives_income_mfda                       INTEGER,
    investment_objectives_growth_mfda                       INTEGER,
    investment_objectives_maximum_growth_mfda               INTEGER,
    risk_tolerance_low_iiroc                                INTEGER,
    risk_tolerance_medium_iiroc                             INTEGER,
    risk_tolerance_high_iiroc                               INTEGER,
    risk_tolerance_low_mfda                                 INTEGER,
    risk_tolerance_low_to_medium_mfda                       INTEGER,
    risk_tolerance_medium_mfda                              INTEGER,
    risk_tolerance_medium_to_high_mfda                      INTEGER,
    risk_tolerance_high_mfda                                INTEGER,
    time_horizon_iiroc                                      VARCHAR(20)  CHECK (time_horizon_iiroc IN ('1 TO 2 YEARS', '3 TO 5 YEARS', '6 TO 9 YEARS', '10 YEARS AND MORE')),
    time_horizon_mfda                                       VARCHAR(20)  CHECK (time_horizon_mfda IN ('LESS THAN 1 YEAR', 'BETWEEN 1 TO 3 YEARS', 'BETWEEN 4 TO 5 YEARS', 'BETWEEN 6 TO 9 YEARS', 'MORE THAN 10 YEARS')),
    kyc_date                                                DATE,
    kyc_reviewed_date                                       DATE,
    comment                                                 VARCHAR(255),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (client_id)
);

CREATE TABLE client.client_language
(
    client_id       INTEGER REFERENCES client.client (client_id) ON DELETE CASCADE,
    language_code   VARCHAR(2)  REFERENCES reference.language(language_code),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (client_id, language_code)

);


CREATE TABLE client.account
(
    account_id                                          SERIAL,
    platform_internal_account_id                        VARCHAR(25),
    advisor_code                                        INTEGER  REFERENCES advisor.advisor_code (advisor_code),
    account_ownership                                   VARCHAR(30) NOT NULL  CHECK (account_ownership IN ('CORPORATE ACCOUNT', 'INDIVIDUAL ACCOUNT', 'INDIVIDUAL TRUST ACCOUNT', 'JOINT ACCOUNT', 'JOINT TRUST ACCOUNT', 'JOINT TRUST ACCOUNT WITH RIGHTS OF SURVIVORSHIP', 'MANAGED ACCOUNT', 'TENANTS IN COMMON')),
    account_type                                        VARCHAR(30) NOT NULL  CHECK (account_ownership IN ('CASH (CAD / USD)', 'DELIVERY AGAINST PAYMENT (DAP) (CAD / USD)', 'LEVERAGE LOAN (CAD ONLY)', 'LEVERAGE LOAN (CAD / USD)', 'MARGIN (CAD / USD)', 'RESP', 'RESP (CAD ONLY)', 'RRIF / LIF', 'RRIF / LIF (CAD ONLY)', 'RRSP / LIRA', 'RRSP/LIRA (CAD ONLY)', 'SPOUSAL RRSP', 'SPOUSAL RRSP (CAD ONLY)', 'TFSA', 'TFSA (CAD ONLY)')),
    client_name_account                                 BOOLEAN,
    nominee_account                                     BOOLEAN,
    internal_account_number                             VARCHAR(15),
    external_account_number                             VARCHAR(15),
    delivery_institution_name                           VARCHAR(255),
    delivery_institution_address_id                     INTEGER  REFERENCES reference.address(address_id),
    delivery_institution_client_account_number          VARCHAR(15),
    delivery_institution_fins_number                    VARCHAR(15),
    delivery_institution_cuid                           VARCHAR(4),
    account_performance_money_weighted                             DECIMAL(6, 2),
    account_performance_time_weighted                              DECIMAL(6, 2),
    consolidated_objectives_and_risk                    BOOLEAN NOT NULL,
    investment_objectives_income_iiroc                  INTEGER,
    investment_objectives_medium_term_growth_iiroc      INTEGER,
    investment_objectives_long_term_growth_iiroc        INTEGER,
    investment_objectives_speculation_iiroc             INTEGER,
    investment_objectives_liquidity_mfda                INTEGER,
    investment_objectives_income_mfda                   INTEGER,
    investment_objectives_growth_mfda                   INTEGER,
    investment_objectives_maximum_growth_mfda           INTEGER,
    risk_tolerance_low_iiroc                            INTEGER,
    risk_tolerance_medium_iiroc                         INTEGER,
    risk_tolerance_high_iiroc                           INTEGER,
    risk_tolerance_low_mfda                             INTEGER,
    risk_tolerance_low_to_medium_mfda                   INTEGER,
    risk_tolerance_medium_mfda                          INTEGER,
    risk_tolerance_medium_to_high_mfda                  INTEGER,
    risk_tolerance_high_mfda                            INTEGER,
    time_horizon_iiroc                                  VARCHAR(20) CHECK (time_horizon_iiroc IN ('1 TO 2 YEARS', '3 TO 5 YEARS', '6 TO 9 YEARS', '10 YEARS AND MORE')),
    time_horizon_mfda                                   VARCHAR(20) CHECK (time_horizon_mfda IN ('LESS THAN 1 YEAR', 'BETWEEN 1 TO 3 YEARS', 'BETWEEN 4 TO 5 YEARS', 'BETWEEN 6 TO 9 YEARS', 'MORE THAN 10 YEARS')),
    intended_use_of_the_account                         VARCHAR(20) CHECK (intended_use_of_the_account IN ('INCOME GENERATION', 'LONG-TERM INVESTMENT', 'RETIREMENT SAVINGS', 'SAVINGS', 'SHORT-TERM INVESTMENT')),
    third_party_financial_benefits                      BOOLEAN NOT NULL,
    third_party_on_the_account                          BOOLEAN NOT NULL,
    power_of_attorney_on_the_account                    BOOLEAN NOT NULL,
    kyc_date                                            DATE,
    kyc_reviewed_date                                   DATE,
    compound_return_1_year                              DECIMAL(6, 2),
    compound_return_3_year                              DECIMAL(6, 2),
    compound_return_5_year                              DECIMAL(6, 2),
    compound_return_10_year                             DECIMAL(6, 2),
    compound_return_inception                           DECIMAL(6, 2),
    return_ytd                                          DECIMAL(6, 2),
    return_this_year_minus_1                            DECIMAL(6, 2),
    return_this_year_minus_2                            DECIMAL(6, 2),
    return_this_year_minus_3                            DECIMAL(6, 2),
    return_this_year_minus_4                            DECIMAL(6, 2),
    return_this_quarter                                 DECIMAL(6, 2),
    return_this_quarter_minus_1                         DECIMAL(6, 2),
    return_this_quarter_minus_2                         DECIMAL(6, 2),
    return_this_quarter_minus_3                         DECIMAL(6, 2),
    return_this_quarter_percent                         DECIMAL(6, 2),
    return_this_quarter_percent_minus_1                 DECIMAL(6, 2),
    return_this_quarter_percent_minus_2                 DECIMAL(6, 2),
    return_this_quarter_percent_minus_3                 DECIMAL(6, 2),
    load_date       DATE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
    PRIMARY KEY (account_id)
);

CREATE TABLE client.client_account
(
    client_id       INTEGER REFERENCES client.client (client_id),
    account_id  INTEGER REFERENCES client.account (account_id),
    load_date       DATE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (client_id, account_id)
);
